"use client";
import Image from "next/image";
import { useLayoutEffect, useRef } from "react";
import { CalendarPlus, ExternalLink, MapPin } from "lucide-react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { BengaliAlpana } from "@/components/ui/BengaliAlpana";
import { GhotMotif, LalPaarBorder, ShankhaMotif } from "@/components/ornaments/BengaliMotifs";
import { SectionContainer } from "@/components/ui/SectionContainer";
import { SectionTitle } from "@/components/ui/SectionTitle";
import { useWeddingLanguage } from "@/components/WeddingLanguage";
import { eventCalendarHref } from "@/lib/calendar";
import { weddingData } from "@/data/weddingData";

gsap.registerPlugin(ScrollTrigger);

export function Events() {
  const section = useRef<HTMLElement>(null); const { t } = useWeddingLanguage(); const events = weddingData.events.filter((event) => event.visible);
  useLayoutEffect(() => { const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const ctx = gsap.context(() => { const rows = gsap.utils.toArray<HTMLElement>(".event-row"); if (reduced) { gsap.set(".event-image, .event-copy", { autoAlpha: 1, clearProps: "transform" }); return; } rows.forEach((row) => gsap.timeline({ scrollTrigger: { trigger: row, start: "top 78%", once: true } }).fromTo(row.querySelector(".event-image"), { autoAlpha: 0, clipPath: "inset(0 0 100% 0)" }, { autoAlpha: 1, clipPath: "inset(0 0 0% 0)", duration: .8, ease: "power3.inOut" }).fromTo(row.querySelector(".event-copy"), { autoAlpha: 0, y: 24 }, { autoAlpha: 1, y: 0, duration: .65, ease: "power3.out" }, "-=.38")); }, section); return () => ctx.revert(); }, []);
  if (!events.length) return null;
  return <section ref={section} id="events" className="relative overflow-hidden bg-secondary px-6 py-24 sm:py-36"><ShankhaMotif className="pointer-events-none absolute -right-8 top-32 hidden w-40 rotate-12 text-maroon/10 lg:block"/><SectionContainer><SectionTitle eyebrow={t(weddingData.ui.events.eyebrow)} title={t(weddingData.ui.events.title)}/><div className="mt-20 space-y-24 sm:space-y-32">{events.map((event, index) => { const reversed = index % 2 === 1; return <article key={`${event.title}-${event.date}`} className="event-row grid items-center gap-10 lg:grid-cols-2 lg:gap-20"><div className={`event-image invisible relative mx-auto w-full max-w-xl ${reversed ? "lg:order-2" : ""}`}><span className="absolute -left-3 -top-3 z-10 h-16 w-16 border-l border-t border-gold"/><div className="image-zoom relative aspect-[5/4] overflow-hidden rounded-sm bg-dark-maroon"><Image src={event.image ?? weddingData.couple.coupleImage} alt={event.imageAlt ?? `${event.title} placeholder`} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/></div><span className="absolute -bottom-3 -right-3 h-16 w-16 border-b border-r border-gold"/></div><div className={`event-copy invisible ${reversed ? "lg:order-1 lg:text-right" : ""}`}><div className={`flex items-center ${reversed ? "lg:flex-row-reverse" : ""}`}><GhotMotif className="w-12 text-gold"/></div><p className="type-caption mt-5 text-gold">{t(event.title)}</p><h3 className="font-display mt-2 text-4xl text-dark-maroon">{t(event.titleBengali)}</h3><div className={`my-6 flex items-center gap-3 ${reversed ? "lg:flex-row-reverse" : ""}`}><span className="h-px w-16 bg-gold/70"/><BengaliAlpana className="w-20 text-gold"/></div><p className="font-display text-xl text-dark-maroon">{event.day} · {event.date} · {event.time}</p><p className={`mt-3 flex items-center gap-2 text-sm text-muted ${reversed ? "lg:flex-row-reverse" : ""}`}><MapPin size={15}/><span>{event.venue}, {event.address}</span></p><div className={`mt-7 flex flex-wrap gap-4 ${reversed ? "lg:justify-end" : ""}`}><a href={eventCalendarHref(event)} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 border-b border-gold pb-1 text-sm font-semibold text-dark-maroon transition hover:text-maroon"><CalendarPlus size={16}/>{t("Add to Calendar")}</a>{event.googleMapsUrl && <a href={event.googleMapsUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 border-b border-gold pb-1 text-sm font-semibold text-dark-maroon transition hover:text-maroon"><span>{t(weddingData.ui.venue.directionsLabel)}</span><ExternalLink size={14}/></a>}</div></div></article>; })}</div></SectionContainer><LalPaarBorder className="absolute inset-x-0 bottom-0 h-3 w-full text-sindoor"/></section>;
}
