"use client";
import Image from "next/image";
import { useLayoutEffect, useRef } from "react";
import { gsap } from "gsap";
import { useInvitationReady } from "@/components/InvitationExperience";
import { useWeddingLanguage } from "@/components/WeddingLanguage";
import { weddingData } from "@/data/weddingData";

export function Hero() {
  const ready = useInvitationReady(); const { t } = useWeddingLanguage();
  const root = useRef<HTMLElement>(null); const image = useRef<HTMLDivElement>(null); const label = useRef<HTMLParagraphElement>(null); const bride = useRef<HTMLHeadingElement>(null); const ampersand = useRef<HTMLSpanElement>(null); const groom = useRef<HTMLHeadingElement>(null); const details = useRef<HTMLDivElement>(null);
  useLayoutEffect(() => { if (!ready) return; const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const ctx = gsap.context(() => { const targets = [image.current, label.current, bride.current, ampersand.current, groom.current, details.current]; if (reduced) { gsap.set(targets, { autoAlpha: 1, clearProps: "transform" }); return; } gsap.timeline().fromTo(image.current, { scale: 1.06 }, { scale: 1, duration: 1.6, ease: "power2.out" }).fromTo(label.current, { autoAlpha: 0, y: 10 }, { autoAlpha: 1, y: 0, duration: .45 }, "-=1.1").fromTo(bride.current, { autoAlpha: 0, y: 35 }, { autoAlpha: 1, y: 0, duration: .65, ease: "power3.out" }, "-=.1").fromTo(ampersand.current, { autoAlpha: 0, scale: .7 }, { autoAlpha: 1, scale: 1, duration: .35 }, "-=.2").fromTo(groom.current, { autoAlpha: 0, y: 35 }, { autoAlpha: 1, y: 0, duration: .65, ease: "power3.out" }, "-=.15").fromTo(details.current, { autoAlpha: 0, y: 16 }, { autoAlpha: 1, y: 0, duration: .45 }, "-=.15"); }, root); return () => ctx.revert(); }, [ready]);
  const { couple, wedding, ui } = weddingData;
  return <section ref={root} id="top" className="relative isolate flex min-h-screen items-center justify-center overflow-hidden bg-dark-maroon px-6 py-28 text-center"><div ref={image} className="absolute inset-0 -z-20"><Image src={couple.heroImage} alt="Bengali wedding invitation background" fill priority quality={80} className="object-cover" sizes="100vw"/></div><div className="absolute inset-0 -z-10 bg-dark-maroon/70"/><div className="relative max-w-6xl"><p ref={label} className="invisible eyebrow !text-gold">{t(ui.hero.label)}</p><div className="mx-auto mt-6 h-px w-16 bg-gold"/><div className="mt-8 flex items-center justify-center gap-3 whitespace-nowrap sm:gap-5"><h1 ref={bride} className="invisible font-display pb-3 text-[clamp(3.25rem,10vw,7.5rem)] leading-[1.05] text-background">{couple.brideName}</h1><span ref={ampersand} className="invisible font-display inline-block pb-2 text-[clamp(2.25rem,4vw,4rem)] text-gold">&amp;</span><h2 ref={groom} className="invisible font-display pb-3 text-[clamp(3.25rem,10vw,7.5rem)] leading-[1.05] text-background">{couple.groomName}</h2></div><div ref={details} className="invisible mx-auto mt-9 max-w-md"><p className="font-display text-xl text-background">{wedding.heroDate} · {wedding.time}</p><p className="type-body mt-4 whitespace-pre-line text-background/80">{wedding.heroMessage}</p></div></div></section>;
}
