"use client";
import Image from "next/image";
import { useLayoutEffect, useRef } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useWeddingLanguage } from "@/components/WeddingLanguage";
import { weddingData } from "@/data/weddingData";

gsap.registerPlugin(ScrollTrigger);

export function Invitation() {
  const section = useRef<HTMLElement>(null); const heading = useRef<HTMLHeadingElement>(null); const body = useRef<HTMLDivElement>(null); const { t } = useWeddingLanguage(); const { hosts, wedding, ui, couple } = weddingData;
  useLayoutEffect(() => { const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const ctx = gsap.context(() => { if (reduced) { gsap.set([heading.current, body.current], { autoAlpha: 1, clearProps: "transform" }); return; } gsap.timeline({ scrollTrigger: { trigger: section.current, start: "top 72%", once: true } }).fromTo(heading.current, { autoAlpha: 0, y: 24 }, { autoAlpha: 1, y: 0, duration: .65, ease: "power3.out" }).fromTo(body.current, { autoAlpha: 0, y: 18 }, { autoAlpha: 1, y: 0, duration: .6, ease: "power3.out" }, "-=.25"); }, section); return () => ctx.revert(); }, []);
  return <section ref={section} id="invitation" className="bg-secondary px-5 py-20 text-center sm:px-6 sm:py-32"><article className="premium-card relative isolate mx-auto max-w-3xl overflow-hidden bg-background px-5 py-11 shadow-[0_24px_60px_rgba(93,10,21,.1)] sm:px-12 sm:py-16">{ui.invitation.backgroundImage && <><Image src={ui.invitation.backgroundImage} alt="" fill loading="lazy" quality={75} className="object-cover" sizes="(max-width: 640px) 100vw, 768px"/><div className="absolute inset-0 bg-background/20"/></>}<div className="relative z-10"><p className="eyebrow text-maroon">{t(ui.invitation.eyebrow)}</p><p className="type-caption mt-3 text-gold">{t(ui.hero.subLabel)}</p><h2 ref={heading} className="invisible type-section-heading mx-auto mt-5 max-w-2xl text-dark-maroon">{t(ui.invitation.heading)}</h2><div className="mx-auto mt-7 flex w-28 items-center gap-3"><span className="h-px flex-1 bg-gold/70"/><span className="h-1.5 w-1.5 rotate-45 bg-maroon"/><span className="h-px flex-1 bg-gold/70"/></div><div ref={body} className="invisible"><div className="mx-auto mt-9 max-w-xl border-y border-gold/35 px-1 py-6 sm:px-6"><p className="type-caption text-gold">{t(hosts.relationToBride)}</p><p className="mx-auto mt-4 text-sm leading-7 text-muted">{hosts.englishInvitation}</p></div><p className="font-display mx-auto mt-9 max-w-2xl whitespace-pre-line text-[1.35rem] leading-9 text-dark-maroon sm:text-2xl sm:leading-10">{wedding.invitationMessage}</p><div className="mx-auto mt-9 h-px w-16 bg-gold"/><div className="mx-auto mt-7 max-w-md"><p className="font-display text-3xl text-maroon sm:text-4xl">{couple.brideName} <span className="px-2 text-gold">&amp;</span> {couple.groomName}</p><p className="font-display mt-4 text-lg italic text-dark-maroon sm:text-xl">{t(wedding.signOff)}</p></div></div></div></article></section>;
}
